name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    strategy:
      matrix:
        react: [18, 19]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/Jod"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          yarn install

          # Overwrite react dependencies to test compatibility with different versions
          yarn add -D \
            react@${{ matrix.react }} \
            react-dom@${{ matrix.react }} \
            @types/react@${{ matrix.react }} \
            @types/react-dom@${{ matrix.react }} \

      - name: Run build
        run: yarn build

      - name: Run typecheck
        run: yarn typecheck
