name: Build

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/Jod"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build
